### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [omelkonian/afp-project#10]
Hi,
I have design this logo for an Algorithm Music project, if you like you can keap it for this project.
If you want it I will give you all the formats of the design free. If you want to make changes please specify.

Greetings

![algo](https://user-images.githubusercontent.com/34600369/39490606-4ddcbbde-4d81-11e8-9972-2315d0e0950a.png)

**Comment by omelkonian** [comment]
Appreciate the gesture, but we are happy with the current (more relevant) logo :)
